spring:
  application:
    name: Usuario API
  datasource:
    url: jdbc:h2:mem:usuario
    username: sa
    password: senha
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
